"""Generate tables to original

Revision ID: 8a46813ce79b
Revises: da4b21721b8f
Create Date: 2023-10-10 22:31:19.139128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a46813ce79b'
down_revision: Union[str, None] = 'da4b21721b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('votes',
                    sa.Column('post_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['post_id'], ['posts.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('post_id', 'user_id')
                    )
    # op.drop_table('products')
    op.add_column('posts', sa.Column('published', sa.Boolean(),
                  server_default='True', nullable=False))
    op.add_column('posts', sa.Column('created_at', sa.TIMESTAMP(
        timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('posts', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'posts', 'users', ['owner_id'], [
                          'id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'owner_id')
    op.drop_column('posts', 'created_at')
    op.drop_column('posts', 'published')
    # op.create_table('products',
    #                 sa.Column('name', sa.VARCHAR(),
    #                           autoincrement=False, nullable=False),
    #                 sa.Column('price', sa.INTEGER(),
    #                           autoincrement=False, nullable=False),
    #                 sa.Column('id', sa.INTEGER(),
    #                           autoincrement=True, nullable=False),
    #                 sa.Column('is_sale', sa.BOOLEAN(), server_default=sa.text(
    #                     'false'), autoincrement=False, nullable=True),
    #                 sa.Column('inventory', sa.INTEGER(), server_default=sa.text(
    #                     '0'), autoincrement=False, nullable=False),
    #                 sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(
    #                     'now()'), autoincrement=False, nullable=False),
    #                 # sa.PrimaryKeyConstraint('id', name='products_pkey')
    #                 )
    op.drop_table('votes')
    op.drop_table('users')
    # ### end Alembic commands ###
