name: Build and deploy

on: [push, pull_request]
jobs:
  job1:
   runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses:  actions/checkout@v4
      - name: say hi to skdlj
        run: echo  ${{ github.repository }}
